### ISSUE TITLE
Output name print doesnt work with origin type string

### ISSUE THREAD

**Issue by dteskera** [phseiff/github-flavored-markdown-to-html#15]
`gh_md_to_html.main(md_as_string, origin_type='string', output_name='print')`

the problem is that html_rendered is returned only if output_pdf is set.

**Comment by phseiff** [comment]
Thanks for pointing that out; seems like I messed up the indentation there! It should be fixed now (Prints no matter whether `output_pdf` is set or not). The new version on PyPi (1.3.3) should behave as expected.
