### ISSUE TITLE
GIFs cannot be hashed

### ISSUE THREAD

**Issue by janniklasrose** [phseiff/github-flavored-markdown-to-html#52]
## Problem

The following MWE

```markdown
![Earth](./Rotating_earth_(large).gif)
```

with the following (any) local GIF fails to convert.

![Rotating_earth_(large)](https://user-images.githubusercontent.com/13775259/127520896-27be8ad5-3f55-43be-b794-e4261cb4ed49.gif)

## Reason

https://github.com/phseiff/github-flavored-markdown-to-html/blob/a3f21df18351afd5aeb1aa5bd57f0f5bae6d9b00/src/__init__.py#L609-L610

`list(img.getdata())` returns a simple `list` of `int`s for GIFs instead of a `list` of `tuple`s (PNGs etc).

**Comment by janniklasrose** [comment]
I'm not sure if this applies to all GIFs or just the two that I have tested (mine is b/w so I thought that might be a reason, but I can replicate the issue with the attached colour GIF from wikipedia). Presumably this is down to how the `PIL.Image` handles the files

**Comment by phseiff** [comment]
This is fixed alongside #54 now; as stated in https://github.com/phseiff/github-flavored-markdown-to-html/pull/53#issuecomment-890421052:

> I released a new version `v1.17.6` (to which you can update e.g. via `pip3 install --upgrade gh-md-to-html>=1.17.6`).
> The new version
>  * supports hashing of GIFs by converting them from paletted color mode to RGBA before creating the hash (therefore properly distinguishing between GIFs that differ in their color palette whilst displaying the same shapes and forms, and properly recognizing two identical GIFs with a differently indexed color palette as identical), 
> * supports hashing animated GIFs (framerate-sensitive), and supports saving animated GIFs correctly,
> * doesn't try to compress GIFs if image compression is enabled anymore.
